// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EssentialExtensions
{
    static class Vsix
    {
        public const string Id = "B485A30F-B8A4-4508-B2B3-D96D529171DD";
        public const string Name = "Essential Extensions";
        public const string Description = @"An opinionated set of extensions to improve the Visual Studio editing experience.";
        public const string Language = "en-US";
        public const string Version = "0.5";
        public const string Author = "Scott Dorman";
        public const string Tags = "extensions, vsix, install";
    }
}
