// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EssentialExtensions.Web
{
    static class Vsix
    {
        public const string Id = "673DC35F-A9E2-426B-98AF-27F51190D0B4";
        public const string Name = "Essential Extensions Web";
        public const string Description = @"An extension pack to improve the Visual Studio editing experience for web development.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Scott Dorman";
        public const string Tags = "extensions, vsix, install";
    }
}
