// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EssentialExtensions.Web
{
    internal sealed partial class Vsix
    {
        public const string Id = "673DC35F-A9E2-426B-98AF-27F51190D0B4";
        public const string Name = "Essential Extensions Web";
        public const string Description = @"An extension pack to improve the Visual Studio editing experience for web development.";
        public const string Language = "en-US";
        public const string Version = "1.4";
        public const string Author = "Scott Dorman";
        public const string Tags = "coding, web, essential-extensions, extensions";
    }
}
